#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  9 14:03:40 2020

@author: joel
"""

import numpy as np
import base_functions as bf
import matplotlib.pyplot as plt


U = np.array([1,1,1, 2,3,3,3])
U_min = min(U)
U_max = max(U)
u = np.linspace(U_min, U_max, 10*int(U_max-U_min)+1)


N = bf.getBaseFunc(U, 0)

plt.plot(u,N(u))















